### ISSUE TITLE
GitHubの.mdファイルへの直リンクがhtmlに書き換えられてしまう

### ISSUE THREAD

**Issue by quojama** [vssio/vss#44]
## 起こった現象

vssを使った自分のサイト (https://pistachiostudio.net/) でローカル作業中に気がついたのですが、

GitHub上の.mdファイル (例: https://github.com/pistachiostudio/main/blob/main/docs/20230226book.md)

への直リンクを記載したかったので、

```markdown
[直リンク](https://github.com/pistachiostudio/main/blob/main/docs/20230226book.md)
```

としたところビルド後、

```
https://github.com/pistachiostudio/main/blob/main/docs/20230226book.html
```

と末尾がhtmlに書き換えられ、404になってしまいました！

**Comment by zztkm** [comment]
たし 🦀

**Comment by zztkm** [comment]
変換ルールを変更することで対応します。

- 現在
  - md 拡張子がついてるリンク形式を html に変換している
- これから
  - 上記の変換処理をなくす
  - 変換をなくした場合、サイト内リンクにしたい場合は root からの path をこのようにする
    - app_dir/hello.md の場合 -> `app_dir/hello`
